apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sczfg8tzu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sczfg8tzu-nodejs 
  name: sczfg8tzu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sczfg8tzu-nodejs 
